### ISSUE TITLE
It seems like Gated S4 is not used.

### ISSUE THREAD

**Issue by Haawron** [md-mohaiminul/TranS4mer#1]
Thanks for the amazing work and sharing tidy codes! As I'm looking into your code, I've found something different from as expected. It seems like S4 used is just its vanilla version instead of Gated S4.

Referring to `trans4mer/pretrain/cfg/default.yaml`, the option block of the model used is like below
```yaml
  MODEL:
    use_sync_bn: True  # for sync_batchnorm in PYL
    shot_encoder:
      name: vit
      resnet:
        input_shape: [3, 224, 224]
        depth: 50
        use_imagenet_pretrained: True  # use 3-channel 2D ResNet pretrained on ImageNet.
        params:
          zero_init_residual: True
          in_channel_dim: 3
      videoswin:
        img_size: 224
        num_classes: 2
        num_frames: 17
        attention_type: divided_space_time
      vit:
        img_size: 224
        use_cls_attn: True
        attention_type: s4
    contextual_relation_network:  # CRN
      enabled: True
      name: trn
      params:
        trn:
          input_dim: 384
          is_decoder: False
          add_cross_attention: False
          chunk_size_feed_forward: 0
          attention_probs_dropout_prob: 0.1
          hidden_act: gelu
          hidden_dropout_prob: 0.1
          hidden_size: 768
          intermediate_size: 3072
          layer_norm_eps: 1e-12
          num_attention_heads: 8
          num_hidden_layers: 2
          pooling_method: center
```
and referring to `trans4mer/model/timm/models/vision_transformer.py`, when `attention_type` is `'s4'`, an atomic block adopts a vanilla S4.
```python
class Block(nn.Module):

    def __init__(
            self, dim, num_heads, mlp_ratio=4., qkv_bias=False, drop=0., attn_drop=0., init_values=None,
            drop_path=0., act_layer=nn.GELU, norm_layer=nn.LayerNorm, attention_type='spatial'):
        super().__init__()
        self.norm1 = norm_layer(dim)
        # ★★★★★★★ HERE ★★★★★★★
        # I think GS4 should replace the attention block below
        self.attn = Attention(dim, num_heads=num_heads, qkv_bias=qkv_bias, attn_drop=attn_drop, proj_drop=drop)
        self.ls1 = LayerScale(dim, init_values=init_values) if init_values else nn.Identity()
        # NOTE: drop path for stochastic depth, we shall see if this is better than dropout here
        self.drop_path1 = DropPath(drop_path) if drop_path > 0. else nn.Identity()

        self.norm2 = norm_layer(dim)
        self.mlp = Mlp(in_features=dim, hidden_features=int(dim * mlp_ratio), act_layer=act_layer, drop=drop)
        self.ls2 = LayerScale(dim, init_values=init_values) if init_values else nn.Identity()
        self.drop_path2 = DropPath(drop_path) if drop_path > 0. else nn.Identity()
        self.attention_type = attention_type

        if attention_type in ['cls', 'joint', 's4']:
            self.aux_norm = norm_layer(dim)
            if attention_type=='s4':  # ★★★★★★★ HERE ★★★★★★★
                self.aux_attn = S4(d_model=dim, l_max=950, bidirectional=True, postact='glu', dropout=attn_drop, transposed=True)
            else:
                self.aux_attn = Attention(dim, num_heads=num_heads, qkv_bias=qkv_bias, attn_drop=attn_drop, proj_drop=drop)
            self.aux_fc = nn.Linear(dim, dim)
            self.aux_drop = DropPath(drop_path) if drop_path > 0. else nn.Identity()
```

I found that attention type is `'gs4'` in the default finetuning config file, but I cannot find any block calling the GS4 module or handling that option.

Could you help me to reproduce your results with GS4?
